// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/binding-service/proto/subscribetopic/subscribetopic.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_binding_subscribetopic is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/binding-service/proto/subscribetopic/subscribetopic.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_kernel_binding_subscribetopic

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Topic            *string `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	Queue            *string `protobuf:"bytes,2,req,name=queue" json:"queue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *Request) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

type Response struct {
	Ok               *bool  `protobuf:"varint,1,req,name=ok" json:"ok,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

func init() {
}
