// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/binding-service/proto/rule.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_binding is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/binding-service/proto/rule.proto

It has these top-level messages:
	BindingRule
*/
package com_HailoOSS_kernel_binding

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BindingRule struct {
	Service          *string `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Version          *string `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Weight           *int32  `protobuf:"varint,3,req,name=weight" json:"weight,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BindingRule) Reset()         { *m = BindingRule{} }
func (m *BindingRule) String() string { return proto.CompactTextString(m) }
func (*BindingRule) ProtoMessage()    {}

func (m *BindingRule) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *BindingRule) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *BindingRule) GetWeight() int32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

func init() {
}
